### ISSUE TITLE
[UX] config options should be in vertical tabs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/disable_term_node_listings#1]
It would look a lot cleaner to move these settings into the vertical tab structure:

<img width="616" alt="screen shot 2017-02-10 at 10 47 12 pm" src="https://cloud.githubusercontent.com/assets/871421/22851293/f649e43e-efe2-11e6-9799-4f1a883cfd7f.png">

**Comment by laryn** [comment]
Maybe this will give some guidance:

https://github.com/backdrop-contrib/taxonomy_menu/commit/0f9d1bbc3d5287ea86902fa69273edd297c8a6f4

**Comment by klonos** [comment]
@laryn, sorry, I meant to file a PR, but instead did a direct commit (and then another to add the missing .js). I googled how to revert commits, but they say that reverting a commit is a commit itself :disappointed:

Please excuse my clumsiness. FTR, can you please verify that my code changes work?

**Comment by laryn** [comment]
@klonos No problem. I did the same before. :) I will test and issue a release if it looks good.

Thanks for pitching in!

**Comment by laryn** [comment]
Beautiful -- thanks! I just tweaked the front-facing language per our discussion on Gitter (#2).
