### ISSUE TITLE
No default when creating a new vocabulary.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/disable_term_node_listings#3]
![backdrop-disable_term_node_listings-no_default_when_creating_vocabulary](https://cloud.githubusercontent.com/assets/2423362/22985975/36ec06c4-f3fe-11e6-9273-c0a6adaa843a.png)

---
PR by @klonos: https://github.com/backdrop-contrib/disable_term_node_listings/pull/4

**Comment by klonos** [comment]
...with a PR this time 😄

**Comment by laryn** [comment]
Thanks again!
